//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndAsisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int IdAsistencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdAlumno { get; set; }
        public int IdEnumAsis { get; set; }
        public int IdDocente { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual EmunAsi EmunAsi { get; set; }
    }
}
