//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndAsisApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colegio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colegio()
        {
            this.Gradoes = new HashSet<Grado>();
        }
    
        public int idColegio { get; set; }
        public string NomColegio { get; set; }
        public int IdAnioElectivo { get; set; }
        public int IdDepartamento { get; set; }
        public int IdDirector { get; set; }
    
        public virtual AnioElectivo AnioElectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grado> Gradoes { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Director Director { get; set; }
    }
}
