//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndAsisApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAsisApp : DbContext
    {
        public DBAsisApp()
            : base("name=DBAsisApp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<AnioElectivo> AnioElectivoes { get; set; }
        public virtual DbSet<Asistencia> Asistencias { get; set; }
        public virtual DbSet<Colegio> Colegios { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Docente> Docentes { get; set; }
        public virtual DbSet<EmunAsi> EmunAsis { get; set; }
        public virtual DbSet<Grado> Gradoes { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
    }
}
